# Generated by Django 5.2.4 on 2026-03-05 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='slot_time',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='status',
        ),
        migrations.AddField(
            model_name='slot',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='slot',
            name='time',
            field=models.CharField(default='9:00 AM', max_length=20),
            preserve_default=False,
        ),
    ]
