# Generated by Django 5.2.4 on 2026-03-07 06:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_remove_slot_slot_time_remove_slot_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='time',
        ),
        migrations.AddField(
            model_name='slot',
            name='end_time',
            field=models.TimeField(default=datetime.time(0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slot',
            name='name',
            field=models.CharField(default=datetime.time(0, 0), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slot',
            name='start_time',
            field=models.TimeField(default=datetime.time(0, 0)),
            preserve_default=False,
        ),
    ]
